# docker-compose.yml
version: '2.2'
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=auth
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./database/db:/data/db
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://user:pass@mongo:27017/auth
    links:
      - mongo
    restart: unless-stopped
    ports:
      - '8081:8081'
